#' Generate a template for a CALMET input file
#' @description Generate a template for a CALMET input file.
#' @export calmet_inp_generate_template

calmet_inp_generate_template <- function(){
  
  writeLines(
    c("CALMET.INP      2.1             Hour Start and End Times with Seconds",
      "",
      "",
      "0 -- Input and Output File Names",
      "",
      "Input files",
      "! GEODAT = !",
      "! SRFDAT = !",
      "! CLDDAT = !",
      "! PRCDAT = !",
      "! WTDAT  = !",
      "",
      "Output files",
      "! METLST = !",
      "! METDAT = !",
      "! PACDAT = !",
      "",
      "! LCFILES = !",
      "",
      "Number of upper air stations and overwater met stations",
      "! NUSTA  = !",
      "! NOWSTA = !",
      "",
      "Number of prognostic and IGF-CALMET files",
      "! NM3D = !",
      "! NIGF = !",
      "",
      "! END ! // end SECTION 0 - Part A",
      "",
      "Upper air files (one per station)",
      "! UPDAT = !",
      "",
      "! END ! // end SECTION 0 - Part B",
      "",
      "Overwater station files (one per station)",
      "! SEADAT = !",
      "",
      "! END !  // end SECTION 0 - Part C",
      "",
      "",
      "MM4/MM5/3D.DAT files (consecutive or overlapping)",
      "! M3DDAT = !",
      "",
      "! END !  // end SECTION 0 - Part D",
      "",
      "IGF-CALMET.DAT files (consecutive or overlapping)",
      "! IGFDAT = !",
      "",
      "! END !  // end SECTION 0 - Part E",
      "",
      "Other CALMET modeling files",
      "",
      "! DIADAT = !",
      "! PRGDAT = !",
      "",
      "! TSTPRT = !",
      "! TSTOUT = !",
      "! TSTKIN = !",
      "! TSTFRD = !",
      "! TSTSLP = !",
      "! DCSTGD = !",
      "",
      "! END ! // end SECTION 0",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "1 -- Temporal Parameters",
      "",
      "Starting date/time",
      "! IBYR  = !",
      "! IBMO  = !",
      "! IBDY  = !",
      "! IBHR  = !",
      "! IBSEC = !",
      "",
      "Ending date/time",
      "! IEYR  = !",
      "! IEMO  = !",
      "! IEDY  = !",
      "! IEHR  = !",
      "! IESEC = !",
      "",
      "UTC time zone",
      "! ABTZ = !",
      "",
      "Length of modeling time-step (seconds)",
      "! NSECDT = !",
      "",
      "Run parameters",
      "! IRTYPE  = !",
      "! LCALGRD = !",
      "! ITEST   = !",
      "! MREG    = !",
      "",
      "! END ! // end SECTION 1",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "2 -- Map projection, datum, grid definitions",
      "",
      "! PMAP   = !",
      "! FEAST  = !",
      "! FNORTH = !",
      "! IUTMZN = !",
      "! UTMHEM = !",
      "! RLAT0  = !",
      "! RLON0  = !",
      "! XLAT1  = !",
      "! XLAT2  = !",
      "",
      "! DATUM = !",
      "",
      "! NX      = !",
      "! NY      = !",
      "! DGRIDKM = !",
      "! XORIGKM = !",
      "! YORIGKM = !",
      "",
      "! NZ    = !",
      "! ZFACE = !",
      "  ",
      "! END ! // end SECTION 2",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "3 -- Output Options",
      " ",
      "! LSAVE     = !",
      "! IFORMO    = !",
      "! LPRINT    = !",
      "! IPRINF    = !",
      "! IUVOUT    = !",
      "! IWOUT     = !",
      "! ITOUT     = !",
      "! STABILITY = !",
      "! USTAR     = !",
      "! MONIN     = !",
      "! MIXHT     = !",
      "! WSTAR     = !",
      "! PRECIP    = !",
      "! SENSHEAT  = !",
      "! CONVZI    = !",
      "",
      "Testing and debug print options for micrometeorological module",
      "",
      "! LDB    = !",
      "! NN1    = !",
      "! NN2    = !",
      "! LDBCST = !",
      "! IOUTD  = !",
      "! NZPRN2 = !",
      "! IPR0   = !",
      "! IPR1   = !",
      "! IPR2   = !",
      "! IPR3   = !",
      "! IPR4   = !",
      "! IPR5   = !",
      "! IPR6   = !",
      "! IPR7   = !",
      "! IPR8   = !",
      "",
      "! END ! // end SECTION 3",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "4 -- Meteorological data options",
      "",
      "Combinations of observations and prognostic data",
      "! NOOBS = !",
      "",
      "Numbers of surface met and precipitation stations",
      "! NSSTA = !",
      "! NPSTA = !",
      "",
      "Cloud data options",
      "! ICLOUD = !",
      "",
      "File formats",
      "! IFORMS = !",
      "! IFORMP = !",
      "! IFORMC = !",
      "",
      "! END ! // end SECTION 4",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "5 -- Wind field options and parameters",
      "",
      "! IWFCOD  = !",
      "! IFRADJ  = !",
      "! IKINE   = !",
      "! IOBR    = !",
      "! ISLOPE  = !",
      "! IEXTRP  = !",
      "! ICALM   = !",
      "! BIAS    = !",
      "! RMIN2   = !",
      "! IPROG   = !",
      "! ISTEPPG = !",
      "! IGFMET  = !",
      "! LVARY   = !",
      "! RMAX1   = !",
      "! RMAX2   = !",
      "! RMAX3   = !",
      "! RMIN    = !",
      "! TERRAD  = !",
      "! R1      = !",
      "! R2      = !",
      "! RPROG   = !",
      "! DIVLIM  = !",
      "! NITER   = !",
      "! NSMTH   = !",
      "! NINTR2  = !",
      "! CRITFN  = !",
      "! ALPHA   = !",
      "! FEXTR2  = !",
      "! NBAR    = !",
      "! KBAR    = !",
      "! XBBAR   = !",
      "! YBBAR   = !",
      "! XEBAR   = !",
      "! YEBAR   = !",
      "! IDIOPT1 = !",
      "! ISURFT  = !",
      "! IDIOPT2 = !",
      "! IUPT    = !",
      "! ZUPT    = !",
      "! IDIOPT3 = !",
      "! IUPWND  = !",
      "! ZUPWND  = !",
      "! IDIOPT4 = !",
      "! IDIOPT5 = !",
      "! LLBREZE = !",
      "! NBOX    = !",
      "! XG1     = !",
      "! XG2     = !",
      "! YG1     = !",
      "! YG2     = !",
      "! XBCST   = !",
      "! YBCST   = !",
      "! XECST   = !",
      "! YECST   = !",
      "! NLB     = ! ",
      "! METBXID = !",
      "",
      "! END ! // end SECTION 5",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "6 -- Mixing height, temperature, and precipitation parameters",
      "",
      "Empirical mixing height constants",
      "! CONSTB  = !",
      "! CONSTE  = !",
      "! CONSTN  = !",
      "! CONSTW  = !",
      "! FCORIOL = !",
      "",
      "Spatial averaging of mixing heights",
      "! IAVEZI = !",
      "! MNMDAV = !",
      "! HAFANG = !",
      "! ILEVZI = !",
      "",
      "Convective mixing height options",
      "! IMIXH   = !",
      "! THRESHL = !",
      "! THRESHW = !",
      "! ITWPROG = !",
      "! ILUOC3D = !",
      "",
      "Other mixing height variables",
      "! DPTMIN = !",
      "! DZZI   = !",
      "! ZIMIN  = !",
      "! ZIMAX  = !",
      "! ZIMINW = !",
      "! ZIMAXW = !",
      "",
      "Overwater surface fluxes methodology and parameters",
      "",
      "! ICOARE = !",
      "! DSHELF = !",
      "! IWARM  = !",
      "! ICOOL  = !",
      "",
      "Temperature parameters",
      "! ITPROG = !",
      "! IRAD   = !",
      "! TRADKM = !",
      "! NUMTS  = !",
      "! IAVET  = !",
      "! TGDEFB = !",
      "! TGDEFA = !",
      "! JWAT1  = !",
      "! JWAT2  = !",
      "",
      "Precipitation interpolation parameters",
      "! NFLAGP = !",
      "! SIGMAP = !",
      "! CUTP   = !",
      "",
      "! END ! // end SECTION 6",
      "",
      "-------------------------------------------------------------------------------",
      "",
      "7 -- Surface meteorological station parameters",
      "",
      "Surface station variables",
      "! SS1  = !",
      "",
      "! END !",
      "",
      "Upper air meteorological station parameters",
      "! US1  = !",
      "",
      "! END !",
      "",
      "Precipitation station parameters",
      "! PS1  =  !",
      "",
      "! END !",
      ""), "calmet_template.txt", sep = "\n")
    
}