#' Create a data frame of discrete receptor concentrations
#' @description Create a data frame of discrete receptor concentrations using a CALPOST time series outfile file.
#' @param time_series_file a path to a time series data file that was generated by CALPOST with the time series option.
#' @export calpost_get_concentrations_from_time_series_file

calpost_get_concentrations_from_time_series_file <- function(time_series_file = NULL,
                                                             location_name,
                                                             source_id,
                                                             pollutant_id){
  
  # Add require statements
  require(stringr)
  require(lubridate)
  
  # Read in all lines from the CALPOST time series output file
  time_series_output <- readLines(time_series_file)
  
  # Get numeric vector of all receptor numbers
  time_series_receptor_numbers <-
    as.numeric(unlist(str_split(gsub("      ix:", "", time_series_output[8]), "          ")))[
      !is.na(as.numeric(unlist(str_split(gsub("      ix:", "", time_series_output[8]), "          "))))]
  
  # Get numeric vector of all x coordinate values (UTM) in units of km
  time_series_x_km <- as.numeric(unlist(str_split(gsub("^.*x......", "", time_series_output[10]), "  ")))
  
  # Get numeric vector of all y coordinate values (UTM) in units of km
  time_series_y_km <- as.numeric(unlist(str_split(gsub("^.*y......", "", time_series_output[11]), "  ")))
  
  # Generate a long data frame containing concentration data for each cell at every timestep
  for (i in 15:length(time_series_output)){
    
    # Initialize a data frame object for containing concentration, date, location, source,
    # pollutant information
    if (i == 15){
      concentration_df <- as.data.frame(mat.or.vec(nr = 0, nc = 12))
      colnames(concentration_df) <- c("posix_date", "year", "month", "day", "hour",
                                      "recep_number", "recep_x_km", "recep_y_km",
                                      "concentration", "location_name", "source_id",
                                      "pollutant_id")
    }
    
    # Extract a string from the 'time_series_output' object, representing data for an hour
    time_series_row <-
      as.vector(as.numeric(unlist(
        str_split_fixed(time_series_output[i],
                        pattern = "[ ]+",
                        n = length(time_series_receptor_numbers) + 4))))
    
  
}
