#' Create a data frame of discrete receptor concentrations
#' @description Create a data frame of discrete receptor concentrations using a CALPOST time series outfile file.
#' @param time_series_file a path to a time series data file that was generated by CALPOST with the time series option.
#' @export calpost_get_concentrations_from_time_series_file

calpost_get_concentrations_from_time_series_file <- function(time_series_file = NULL){
  
  # Add require statements
  require(stringr)
  require(lubridate)
  
  
  
}
